org.gradle.jvmargs=-Xmx4G

minecraft_version=1.21.3

fabric_loader=0.16.14
neoforge_loader=21.3.96
neoforge_loader_dependency=[4,)

fabric_minecraft_dependency=>=1.21.3 <1.21.4
neoforge_minecraft_dependency=[1.21.3,1.21.4)

build_number=1
mod_group=me.noramibu
mod_artifact_name=dynamic-trims
mod_description=Dynamically render Minecraft's Armour Trims patterns
