org.gradle.jvmargs=-Xmx4G

minecraft_version=26.3
minecraft_line=26.3
java_version=25

fabric_loader=0.19.3
neoforge_loader=26.3.0.23-beta
neoforge_loader_dependency=[1,)

fabric_minecraft_dependency=>=26.3 <26.4
neoforge_minecraft_dependency=[26.3,26.4)

build_number=2
mod_group=me.noramibu
mod_artifact_name=dynamic-trims
mod_description=Dynamically render Minecraft's Armour Trims patterns
