org.gradle.jvmargs=-Xmx4G

minecraft_version=26.1.2
minecraft_line=26.1
java_version=25

fabric_loader=0.19.3
neoforge_loader=26.1.2.77
neoforge_loader_dependency=[1,)

fabric_minecraft_dependency=>=26.1 <26.2
neoforge_minecraft_dependency=[26.1,26.2)

build_number=1
mod_group=me.noramibu
mod_artifact_name=dynamic-trims
mod_description=Dynamically render Minecraft's Armour Trims patterns
