modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "MIT"

[[mods]]
modId = "dynamictrim"
version = "${version}"
displayName = "Dynamic Trims"
authors = "noramibu, Bawnorton"
displayURL = "https://modrinth.com/project/dynamic-trims/"
issueTrackerURL = "https://github.com/noramibu/dynamic-trims/issues"
description = '''
${description}
'''
iconFile = "assets/dynamictrim/icon.png"

[modproperties.dynamictrim]
discord = "https://discord.gg/FaxbR9eEFW"

[[mixins]]
config = "dynamictrim-client.mixins.json"

[[mixins]]
config = "dynamictrim-runtime-client.mixins.json"

[[dependencies.dynamictrim]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"
